# Generated by Django 5.0.4 on 2024-04-29 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la categoria')),
                ('nombre_categoria', models.CharField(max_length=60, verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_inventario')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('modelo', models.CharField(max_length=60, verbose_name='modelo')),
                ('imagen', models.ImageField(null=True, upload_to='inventario/', verbose_name='Imagen del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
